# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-27 07:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DomainName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Event_Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Event_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='MonitorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namelookup_time', models.IntegerField(default=None, null=True)),
                ('connect_time', models.IntegerField(default=None, null=True)),
                ('pretransfer_time', models.IntegerField(default=None, null=True)),
                ('starttransfer_time', models.IntegerField(default=None, null=True)),
                ('total_time', models.IntegerField(default=None, null=True)),
                ('http_code', models.IntegerField(default=None, null=True)),
                ('size_download', models.IntegerField(default=None, null=True)),
                ('header_size', models.IntegerField(default=None, null=True)),
                ('request_size', models.IntegerField(default=None, null=True)),
                ('content_length_download', models.IntegerField(default=None, null=True)),
                ('speed_download', models.IntegerField(default=None, null=True)),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='monitordata',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webmoni.Node'),
        ),
        migrations.AddField(
            model_name='monitordata',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webmoni.DomainName'),
        ),
        migrations.AddField(
            model_name='event_log',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webmoni.Event_Type'),
        ),
        migrations.AddField(
            model_name='event_log',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webmoni.Node'),
        ),
        migrations.AddField(
            model_name='event_log',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webmoni.DomainName'),
        ),
    ]
