# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-09 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmoni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainname',
            name='no_check',
            field=models.IntegerField(default=0),
        ),
    ]
