# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-02 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmoni', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainname',
            name='url',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='event_type',
            name='event_type',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='node',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
