# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-02 04:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webmoni', '0002_auto_20180502_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitordata',
            name='content_length_download',
        ),
        migrations.RemoveField(
            model_name='monitordata',
            name='request_size',
        ),
    ]
