# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-09 10:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webmoni', '0002_domainname_no_check'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domainname',
            old_name='no_check',
            new_name='check',
        ),
    ]
