# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-02 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmoni', '0003_auto_20180502_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitordata',
            name='connect_time',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='monitordata',
            name='namelookup_time',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='monitordata',
            name='pretransfer_time',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='monitordata',
            name='starttransfer_time',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='monitordata',
            name='total_time',
            field=models.FloatField(default=None, null=True),
        ),
    ]
