# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-04 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmoni', '0005_auto_20180503_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitordata',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
