# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-11 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webmoni', '0006_domainname_warning'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domainname',
            old_name='check_id',
            new_name='check',
        ),
    ]
