# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-04 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmoni', '0006_auto_20180504_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitordata',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
