# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-14 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmoni', '0008_auto_20180511_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitordata',
            name='datetime',
            field=models.DateTimeField(db_index=True),
        ),
    ]
