# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-16 11:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webmoni', '0010_node_ip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event_type',
            old_name='event_type',
            new_name='type',
        ),
    ]
