# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-08 10:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webmoni', '0010_auto_20180504_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='event_log',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 8, 10, 50, 54, 146681)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='domainname',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webmoni.StatusType'),
        ),
    ]
