# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-08 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webmoni', '0011_auto_20180508_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainname',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webmoni.Event_Type'),
        ),
        migrations.DeleteModel(
            name='StatusType',
        ),
    ]
