# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-16 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webmoni', '0011_auto_20180516_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event_type',
            old_name='type',
            new_name='event_type',
        ),
    ]
