# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-17 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmoni', '0012_auto_20180516_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainname',
            name='cert_valid_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='domainname',
            name='cert_valid_days',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
