# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-18 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmoni', '0014_auto_20180517_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainname',
            name='cert_valid_date',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
