# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-21 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmoni', '0016_auto_20180518_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='description',
            field=models.CharField(max_length=4096, null=True),
        ),
    ]
