# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-23 14:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webmoni', '0018_node_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitordata',
            name='connect_time',
        ),
        migrations.RemoveField(
            model_name='monitordata',
            name='header_size',
        ),
        migrations.RemoveField(
            model_name='monitordata',
            name='namelookup_time',
        ),
        migrations.RemoveField(
            model_name='monitordata',
            name='pretransfer_time',
        ),
        migrations.RemoveField(
            model_name='monitordata',
            name='size_download',
        ),
        migrations.RemoveField(
            model_name='monitordata',
            name='speed_download',
        ),
        migrations.RemoveField(
            model_name='monitordata',
            name='starttransfer_time',
        ),
    ]
