# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-11 16:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webmoni', '0020_auto_20180611_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domainname',
            name='interval',
        ),
        migrations.RemoveField(
            model_name='domainname',
            name='trigger',
        ),
    ]
