# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-21 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webmoni', '0021_auto_20180611_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainname',
            name='status',
            field=models.ForeignKey(default=10, null=True, on_delete=django.db.models.deletion.CASCADE, to='webmoni.Event_Type'),
        ),
    ]
