# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-22 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmoni', '0023_auto_20180622_0538'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainname',
            name='cdn',
            field=models.CharField(default=None, max_length=60, null=True),
        ),
    ]
