# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-29 02:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webmoni', '0024_domainname_cdn'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainToNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webmoni.DomainName')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webmoni.Node')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webmoni.Event_Type')),
            ],
        ),
    ]
