# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-03 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmoni', '0025_domaintonode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domaintonode',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='domaintonode',
            name='node',
        ),
        migrations.RemoveField(
            model_name='domaintonode',
            name='status',
        ),
        migrations.AddField(
            model_name='domainname',
            name='nodes',
            field=models.ManyToManyField(to='webmoni.Node'),
        ),
        migrations.DeleteModel(
            name='DomainToNode',
        ),
    ]
