# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-14 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmoni', '0026_auto_20180703_1046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domainname',
            options={'verbose_name_plural': '域名信息'},
        ),
        migrations.AlterModelOptions(
            name='event_type',
            options={'verbose_name_plural': '事件类型'},
        ),
        migrations.AlterModelOptions(
            name='node',
            options={'verbose_name_plural': '节点'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name_plural': '项目'},
        ),
        migrations.AlterField(
            model_name='node',
            name='online',
            field=models.IntegerField(choices=[(0, '在线'), (1, '离线')], default=None, null=True),
        ),
    ]
