# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-14 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmoni', '0027_auto_20180714_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainname',
            name='check_id',
            field=models.IntegerField(choices=[(0, '检查'), (1, '不检查')], default=0),
        ),
        migrations.AlterField(
            model_name='domainname',
            name='warning',
            field=models.IntegerField(choices=[(0, '警告'), (1, '不警告')], default=0),
        ),
    ]
