# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-14 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accepted_minion',
            fields=[
                ('salt_id', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=60, unique=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('ipv4', models.CharField(blank=True, max_length=60, null=True)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('osfinger', models.CharField(blank=True, max_length=60, null=True)),
                ('cpu_model', models.CharField(blank=True, max_length=60, null=True)),
                ('num_cpus', models.IntegerField(blank=True, null=True)),
                ('mem_total', models.IntegerField(blank=True, null=True)),
                ('mem_gib', models.CharField(blank=True, max_length=10, null=True)),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Async_jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jid', models.CharField(blank=True, max_length=20, null=True)),
                ('number', models.CharField(max_length=20)),
                ('create_time', models.DateTimeField()),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('finish_time', models.DateTimeField(blank=True, null=True)),
                ('information', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, '排队中'), (1, '执行中'), (2, '已完成')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PlayBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_file', models.CharField(blank=True, max_length=100, null=True)),
                ('sls', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=28, null=True)),
                ('status', models.IntegerField(choices=[(0, '禁用'), (1, '可用')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='playbook',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saltstack.Project'),
        ),
        migrations.AddField(
            model_name='async_jobs',
            name='description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saltstack.PlayBook'),
        ),
        migrations.AddField(
            model_name='async_jobs',
            name='minion',
            field=models.ManyToManyField(to='saltstack.Accepted_minion'),
        ),
        migrations.AddField(
            model_name='async_jobs',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saltstack.Project'),
        ),
        migrations.AddField(
            model_name='accepted_minion',
            name='project',
            field=models.ManyToManyField(to='saltstack.Project'),
        ),
    ]
