# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-05 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accepted_minion',
            fields=[
                ('salt_id', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=60, unique=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('ipv4', models.CharField(blank=True, max_length=60, null=True)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('osfinger', models.CharField(blank=True, max_length=60, null=True)),
                ('cpu_model', models.CharField(blank=True, max_length=60, null=True)),
                ('cpuarch', models.CharField(blank=True, max_length=20, null=True)),
                ('num_cpus', models.IntegerField(blank=True, null=True)),
                ('mem_total', models.IntegerField(blank=True, null=True)),
                ('mem_gib', models.CharField(blank=True, max_length=10, null=True)),
                ('datetime', models.DateTimeField()),
            ],
        ),
    ]
