# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-22 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grains_items',
            fields=[
                ('id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('ipv4', models.CharField(default=None, max_length=60, null=True)),
                ('osfullname', models.CharField(max_length=60, null=True)),
                ('cpu_model', models.CharField(max_length=60, null=True)),
                ('cpuarch', models.CharField(max_length=20, null=True)),
                ('num_cpus', models.IntegerField(null=True)),
                ('mem_total', models.IntegerField(null=True)),
                ('datetime', models.DateTimeField()),
            ],
        ),
    ]
