# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-23 01:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saltstack', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grains_items',
        ),
    ]
