# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-23 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('saltstack', '0002_delete_grains_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grains_items',
            fields=[
                ('salt_id', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=60, unique=True)),
                ('ipv4', models.CharField(blank=True, max_length=60, null=True)),
                ('osfullname', models.CharField(blank=True, max_length=60, null=True)),
                ('cpu_model', models.CharField(blank=True, max_length=60, null=True)),
                ('cpuarch', models.CharField(blank=True, max_length=20, null=True)),
                ('num_cpus', models.IntegerField(blank=True, null=True)),
                ('mem_total', models.IntegerField(blank=True, null=True)),
                ('datetime', models.DateTimeField()),
            ],
        ),
    ]
