# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-14 10:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saltstack', '0002_auto_20180714_1001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='async_jobs',
            old_name='info',
            new_name='information',
        ),
    ]
