# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-26 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saltstack', '0004_auto_20180626_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exception_minion',
            fields=[
                ('salt_id', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=60, unique=True)),
                ('exception', models.CharField(max_length=60, unique=True)),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='accepted_minion',
            name='mem_gib',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
