# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-14 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saltstack', '0005_auto_20180714_1014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accepted_minion',
            options={'verbose_name_plural': '主机列表'},
        ),
        migrations.AlterModelOptions(
            name='playbook',
            options={'verbose_name_plural': '剧本'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name_plural': '主机组'},
        ),
        migrations.AlterField(
            model_name='accepted_minion',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, '离线'), (1, '在线'), (2, '检测中')], null=True),
        ),
    ]
