# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-26 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saltstack', '0005_auto_20180626_1126'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exception_minion',
        ),
        migrations.DeleteModel(
            name='Unaccepted_minion',
        ),
        migrations.AddField(
            model_name='accepted_minion',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
