# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-26 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saltstack', '0006_auto_20180626_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accepted_minion',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
