# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-14 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saltstack', '0006_auto_20180714_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='async_jobs',
            name='status',
            field=models.IntegerField(choices=[(0, '排队中'), (1, '执行中'), (2, '已完成'), (3, '异常')], default=0),
        ),
    ]
