# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-21 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.IntegerField()),
                ('node_name', models.CharField(max_length=20, unique=True)),
                ('node_ip', models.CharField(max_length=20, null=True)),
                ('salt_id', models.CharField(max_length=40, null=True)),
                ('os_type', models.CharField(max_length=40, null=True)),
            ],
        ),
    ]
