# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-26 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('online', models.CharField(choices=[('Online', '在线'), ('Offline', '离线'), ('Exception', '异常')], default='Offline', max_length=2)),
            ],
        ),
    ]
